import buildlogic.plugin.InfraPlugin
import buildlogic.task.CleanTempTask
import buildlogic.task.SshTask

apply(plugin: InfraPlugin)

infra {
    loadProperties "local.properties"

    service {
        name "seaweed"
        upCommand {
            workDir seaweedPath
            command "./weed mini -dir=data"
            env([
                AWS_ACCESS_KEY_ID    : "admin",
                AWS_SECRET_ACCESS_KEY: "secret",
                S3_BUCKET            : "s3-bucket"
            ])
            detachAfterPhrase "All enabled components are running and ready to use"
            timeoutSeconds 60
        }
        imageFullPath seaweedPath + seaweedExe
    }

    service {
        name "postgres"
        upCommand {
            workDir postgresPath
            command "./bin/pg_ctl start -D data -l postgres.txt"
            timeoutSeconds 60
        }
        imageFullPath postgresExe
        downCommand {
            workDir postgresPath
            command "./bin/pg_ctl stop -D data"
            timeoutSeconds 60
        }
        healthcheck {
            command {
                workDir postgresPath
                command "./bin/pg_isready -h localhost -d postgres -U postgres"
                timeoutSeconds 60
            }
            intervalSeconds 2
            timeoutSeconds 10
        }
    }

    def remoteHost = remote {
        host sshHost
        port sshPort
        user sshUser
        password sshPassword
    }

    tasks.register('checkRemote', SshTask) {
        group = 'remote'
        remote = remoteHost
        exec 'echo -- Docker && sudo docker ps --format "table {{.ID}}\\t{{.Names}}\\t{{.Status}}"'
        exec 'echo -- Disk && sudo df -h --output=source,avail,pcent'
        exec 'echo -- RAM && free -h'
        exec 'echo -- CPU && mpstat'
    }

    tasks.register('cleanTemp', CleanTempTask) {
        group = 'cleanup'
    }
}