void loadRootProjectProperties() {
    def props = new Properties()
    def gradleProperties = new File("${rootDir.parentFile}/gradle.properties")
    if (gradleProperties.exists()) {
        gradleProperties.withInputStream {
            props.load(it)
        }
    }
    props.each {
        project.ext.set(it.key.toString(), it.value)
    }
}

loadRootProjectProperties()

repositories {
    mavenCentral()
    mavenLocal()
}

dependencies {
    implementation libs.jsch
    implementation libs.commonsLang3
}